"use client";
import { useEffect,useMemo,useState } from "react";
import { FUNDS } from "@/lib/constants";

type Fund=typeof FUNDS[number]&{nav:number;date:string;belowHigh:number;aboveLow:number;below6MHigh:number;above6MLow?:number;rsi:number;ma20:number;ma50:number;crossover:string;return3M:number;return6M:number;r3rank:number;r6rank:number;relRank?:number;relativeStrength?:number;discountScore:number;recoveryScore?:number;momentumScore?:number;overallScore:number;totalScore:number;opportunity:number;selected?:boolean;recommendedPct?:number;recommendedAmount?:number;allocationPct:number;allocation:number;history:Array<{date:string;nav:number}>;error?:string};
type Purchase={code:string;date:string;units:number;amount:number};
const money=(n:number)=>Number.isFinite(n)?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n):"₹0";
const nav=(n:number)=>Number.isFinite(n)?`₹${n.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:4})}`:"—";

export default function HomePage(){
 const[budget,setBudget]=useState(10000),[cadence,setCadence]=useState<"weekly"|"monthly">("monthly"),[data,setData]=useState<Fund[]>([]),[top5,setTop5]=useState<Fund[]>([]),[updated,setUpdated]=useState(""),[loading,setLoading]=useState(true),[selected,setSelected]=useState<string[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[tab,setTab]=useState<"dashboard"|"planner"|"portfolio">("dashboard"),[topN,setTopN]=useState<4|5>(5);
 const load=async()=>{setLoading(true);try{const r=await fetch(`/api/dashboard?budget=${budget}&t=${Date.now()}`,{cache:"no-store"});const j=await r.json();if(!j.success)throw Error(j.error);setData(j.funds);setTop5(j.top5);setUpdated(j.lastUpdated)}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{try{setPurchases(JSON.parse(localStorage.getItem("sip-purchases")||"[]"));const b=Number(localStorage.getItem("sip-budget"));if(b)setBudget(b)}catch{}},[]);useEffect(()=>{load()},[budget]);
 const picks=useMemo(()=>top5.slice(0,topN),[top5,topN]);
 const allocations=useMemo(()=>{if(!picks.length)return[];const w=picks.map(f=>Math.max(1,f.totalScore??0)),s=w.reduce((a,b)=>a+b,0);const out=picks.map((f,i)=>({...f,calcPct:w[i]/s,calcAmount:Math.round(budget*w[i]/s/10)*10}));const diff=budget-out.reduce((a,b)=>a+b.calcAmount,0);if(out.length)out[0].calcAmount+=diff;return out},[picks,budget]);
 const totalInvested=purchases.reduce((s,p)=>s+p.amount,0);const currentValue=purchases.reduce((s,p)=>{const f=data.find(x=>x.amfiCode===p.code);return s+p.units*(f?.nav||0)},0);const gain=currentValue-totalInvested;
 const exportCsv=()=>{const rows=["date,amfiCode,fund,units,amount",...purchases.map(p=>{const f=FUNDS.find(x=>x.amfiCode===p.code);return `${p.date},${p.code},"${f?.name||""}",${p.units},${p.amount}`})];const blob=new Blob([rows.join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sip-purchases.csv";a.click()};
 const toggle=(c:string)=>setSelected(s=>s.includes(c)?s.filter(x=>x!==c):[...s,c].slice(-4));
 return <main className="min-h-screen bg-[#070b14] text-slate-100"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#070b14]/95 backdrop-blur"><div className="mx-auto max-w-[1500px] px-4 py-3 flex flex-wrap gap-3 items-center justify-between"><div><h1 className="text-xl font-black">AI Mutual Fund Investment Engine PRO</h1><p className="text-[11px] text-slate-500">19-fund universe · historical/rule-based decision support · {updated?`NAV updated: ${new Date(updated).toLocaleString("en-IN")}`:"loading…"}</p></div><div className="flex gap-2"><button onClick={()=>setTab("dashboard")} className={`px-3 py-2 rounded-lg text-xs ${tab==="dashboard"?"bg-indigo-600":"bg-white/5"}`}>Dashboard</button><button onClick={()=>setTab("planner")} className={`px-3 py-2 rounded-lg text-xs ${tab==="planner"?"bg-indigo-600":"bg-white/5"}`}>SIP Planner</button><button onClick={()=>setTab("portfolio")} className={`px-3 py-2 rounded-lg text-xs ${tab==="portfolio"?"bg-indigo-600":"bg-white/5"}`}>Portfolio</button><button onClick={load} className="px-3 py-2 rounded-lg text-xs bg-white/5">↻ Refresh</button></div></div></header>
 <div className="mx-auto max-w-[1500px] px-4 py-5 space-y-5"><div className="rounded-xl border border-amber-500/30 bg-amber-950/20 p-3 text-[11px] text-amber-200">⚠️ <b>Heuristic only:</b> Overall Score and Discount Score are historical rule-based signals. Total Score = 70% Overall Score + 30% Discount Score. It does not predict rallies, guarantee a lowest-price entry, or constitute investment advice.</div>
 {tab==="dashboard"&&<><section className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Card t="SIP Budget" v={money(budget)}/><Card t="Selection" v={`Top ${topN}`}/><Card t="Invested" v={money(totalInvested)}/><Card t="Current Value" v={money(currentValue)}/><Card t="Gain / Loss" v={`${money(gain)} (${totalInvested?((gain/totalInvested)*100).toFixed(1):"0.0"}%)`}/></section>
 <section className="rounded-2xl border border-indigo-400/20 bg-gradient-to-br from-indigo-950/60 to-slate-950 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[.25em] text-indigo-300">This period's decision</div><h2 className="text-2xl font-black mt-1">🎯 Top {topN} Funds to Invest</h2><p className="text-xs text-slate-400 mt-1">{cadence==="monthly"?"Monthly":"Weekly"} ranking from all 19 funds · investment budget {money(budget)}</p></div><div className="flex gap-2"><button onClick={()=>setTopN(4)} className={`px-4 py-2 rounded-lg text-xs font-bold ${topN===4?"bg-indigo-600":"bg-white/5"}`}>TOP 4</button><button onClick={()=>setTopN(5)} className={`px-4 py-2 rounded-lg text-xs font-bold ${topN===5?"bg-indigo-600":"bg-white/5"}`}>TOP 5</button><select value={cadence} onChange={e=>setCadence(e.target.value as "weekly"|"monthly")} className="bg-black/30 border border-white/10 rounded-lg px-3 text-xs"><option value="monthly">Monthly</option><option value="weekly">Weekly</option></select></div></div>
 {loading?<div className="p-10 text-center text-slate-500">Analysing 19 funds and fetching NAV history…</div>:<div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3 mt-5">{allocations.map((f,i)=><div key={f.amfiCode} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex justify-between items-center"><span className="text-lg font-black">#{i+1}</span><span className="rounded-full bg-emerald-500/15 text-emerald-300 px-2 py-1 text-[10px]">TOTAL {f.totalScore}</span></div><h3 className="font-bold mt-3">{f.shortName}</h3><div className="text-[10px] text-slate-500">{f.amfiCode}</div><div className="mt-3 rounded-lg border border-indigo-400/15 bg-indigo-500/5 p-3"><div className="text-[10px] text-slate-400">CURRENT NAV</div><div className="text-xl font-black text-white mt-1">{nav(f.nav)}</div><div className="text-[10px] text-slate-500">NAV date: {f.date||"—"}</div></div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><Metric label="Overall Score" value={`${f.overallScore}/100`}/><Metric label="Discount Score" value={`${f.discountScore}/100`}/><Metric label="52W Discount" value={`${f.belowHigh.toFixed(1)}%`} good/><Metric label="6M Discount" value={`${f.below6MHigh.toFixed(1)}%`} good/><Metric label="RSI" value={f.rsi.toFixed(0)}/><Metric label="3M Rank" value={`#${f.r3rank}`}/></div><div className="mt-3 text-[10px] text-slate-400">Total = <b className="text-white">70% Overall + 30% Discount</b></div><div className="mt-3 rounded-lg bg-indigo-500/10 p-3"><div className="text-[10px] text-indigo-300">RECOMMENDED SIP</div><div className="text-xl font-black mt-1">{money(f.calcAmount)}</div><div className="text-[10px] text-slate-500">{(f.calcPct*100).toFixed(1)}% of budget · {cadence}</div></div></div>)}</div>}</section>
 <section className="rounded-xl border border-white/10 bg-white/[.03] overflow-hidden"><div className="p-4 border-b border-white/10"><h2 className="font-bold">19-Fund Ranking, NAV & Discount Analysis</h2><p className="text-[11px] text-slate-500">Top 4/5 selection uses Total Score, not discount alone.</p></div>{loading?<div className="p-8 text-center text-slate-500">Loading…</div>:<div className="overflow-auto"><table className="w-full text-xs"><thead className="text-slate-500 border-b border-white/5"><tr><th className="p-3 text-left">Rank</th><th className="text-left">Fund</th><th>NAV</th><th>Overall</th><th>52W Discount</th><th>Discount Score</th><th>Total</th><th>RSI</th><th>3M</th><th>6M</th><th>Trend</th><th>SIP</th></tr></thead><tbody>{[...data].sort((a,b)=>b.totalScore-a.totalScore).map((f,i)=><tr key={f.amfiCode} className={`border-b border-white/5 ${f.selected?"bg-emerald-500/[.04]":""}`}><td className="p-3 font-bold">#{i+1}</td><td><b>{f.shortName}</b><div className="text-[10px] text-slate-500">{f.amfiCode}</div></td><td className="text-center font-mono">{nav(f.nav)}</td><td className="text-center font-bold">{f.overallScore}</td><td className="text-center text-emerald-300">{f.belowHigh.toFixed(1)}%</td><td className="text-center">{f.discountScore}</td><td className="text-center font-black text-indigo-300">{f.totalScore}</td><td className="text-center">{f.rsi.toFixed(0)}</td><td className="text-center">#{f.r3rank}</td><td className="text-center">#{f.r6rank}</td><td className={`text-center ${f.crossover==="Bullish"?"text-emerald-400":"text-red-400"}`}>{f.crossover}</td><td className="text-center font-bold">{f.selected?money(f.allocation):"—"}</td></tr>)}</tbody></table></div>}</section>
 <section className="rounded-xl border border-white/10 bg-white/[.03] p-4"><h2 className="font-bold mb-3">NAV History Comparison</h2><div className="flex flex-wrap gap-2 mb-3">{data.map(f=><button key={f.amfiCode} onClick={()=>toggle(f.amfiCode)} className={`px-2 py-1 rounded text-[10px] ${selected.includes(f.amfiCode)?"bg-indigo-600":"bg-white/5"}`}>{f.shortName}</button>)}</div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{data.filter(f=>selected.includes(f.amfiCode)).map(f=><div key={f.amfiCode} className="h-28 rounded-lg bg-black/20 p-2"><div className="text-[10px] text-slate-400 mb-2">{f.shortName} · {nav(f.nav)}</div><MiniChart points={f.history.slice(-90).map(x=>x.nav)}/></div>)}</div></section></>}
 {tab==="planner"&&<Planner budget={budget} setBudget={b=>{setBudget(b);localStorage.setItem("sip-budget",String(b))}} cadence={cadence} setCadence={setCadence} picks={allocations}/>} {tab==="portfolio"&&<Portfolio data={data} purchases={purchases} setPurchases={p=>{setPurchases(p);localStorage.setItem("sip-purchases",JSON.stringify(p))}} totalInvested={totalInvested} currentValue={currentValue} gain={gain} exportCsv={exportCsv}/>}</div><footer className="border-t border-white/10 mt-8 py-4 text-center text-[10px] text-slate-600">AI Mutual Fund Investment Engine PRO · 19 funds · Historical heuristics only</footer></main>
}
function Metric({label,value,good}:{label:string;value:string;good?:boolean}){return <div className="rounded bg-white/[.03] p-2"><div className="text-slate-500">{label}</div><div className={good?"text-emerald-300 font-bold mt-1":"font-bold mt-1"}>{value}</div></div>}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="text-[11px] text-slate-500">{t}</div><div className="text-lg font-bold mt-1">{v}</div></div>}
function MiniChart({points}:{points:number[]}){if(!points.length)return <div className="text-[10px] text-slate-600">No history</div>;const min=Math.min(...points),max=Math.max(...points);return <svg viewBox="0 0 300 70" className="w-full h-full"><polyline fill="none" stroke="#818cf8" strokeWidth="2" points={points.map((v,i)=>`${points.length===1?0:i/(points.length-1)*300},${68-(v-min)/Math.max(1,max-min)*60}`).join(" ")}/></svg>}
function Planner({budget,setBudget,cadence,setCadence,picks}:{budget:number;setBudget:(n:number)=>void;cadence:"weekly"|"monthly";setCadence:(x:"weekly"|"monthly")=>void;picks:Fund[]}){return <section className="max-w-5xl mx-auto space-y-4"><div className="rounded-xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-bold">SIP Planner — Top 4/5 Only</h2><div className="grid md:grid-cols-3 gap-4 mt-4"><label className="text-xs text-slate-400">Investment Amount<input type="number" value={budget} onChange={e=>setBudget(Math.max(1000,+e.target.value))} className="mt-1 w-full bg-black/30 border border-white/10 rounded p-2 text-white"/></label><label className="text-xs text-slate-400">Cadence<select value={cadence} onChange={e=>setCadence(e.target.value as "weekly"|"monthly")} className="mt-1 w-full bg-black/30 border border-white/10 rounded p-2 text-white"><option value="monthly">Monthly</option><option value="weekly">Weekly</option></select></label></div></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-5"><h3 className="font-bold mb-3">Current recommended deployment</h3>{picks.map((f,i)=><div key={f.amfiCode} className="flex flex-wrap items-center justify-between gap-2 border-b border-white/5 py-3 text-xs"><span><b>#{i+1} {f.shortName}</b><span className="text-slate-500 ml-2">NAV {nav(f.nav)} · Overall {f.overallScore} · Discount {f.discountScore} · Total {f.totalScore}</span></span><b className="text-emerald-300">{money(f.calcAmount)}</b></div>)}</div></section>}
function Portfolio({data,purchases,setPurchases,totalInvested,currentValue,gain,exportCsv}:{data:Fund[];purchases:Purchase[];setPurchases:(p:Purchase[])=>void;totalInvested:number;currentValue:number;gain:number;exportCsv:()=>void}){const[code,setCode]=useState<string>(FUNDS[0].amfiCode),[units,setUnits]=useState(""),[amount,setAmount]=useState("");const add=()=>{if(!units||!amount)return;setPurchases([...purchases,{code,date:new Date().toISOString().slice(0,10),units:+units,amount:+amount}]);setUnits("");setAmount("")};return <section className="space-y-4"><div className="grid md:grid-cols-3 gap-3"><Card t="Invested" v={money(totalInvested)}/><Card t="Current NAV Value" v={money(currentValue)}/><Card t="Gain / Loss" v={money(gain)}/></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="flex justify-between items-center"><h2 className="font-bold">Purchase Log</h2><button onClick={exportCsv} className="px-3 py-2 rounded bg-indigo-600 text-xs">Export CSV</button></div><div className="grid md:grid-cols-4 gap-2 mt-3"><select value={code} onChange={e=>setCode(e.target.value)} className="bg-black/30 border border-white/10 rounded p-2 text-xs">{FUNDS.map(f=><option key={f.amfiCode} value={f.amfiCode}>{f.shortName}</option>)}</select><input value={units} onChange={e=>setUnits(e.target.value)} placeholder="Units" className="bg-black/30 border border-white/10 rounded p-2 text-xs"/><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Invested ₹" className="bg-black/30 border border-white/10 rounded p-2 text-xs"/><button onClick={add} className="bg-emerald-600 rounded p-2 text-xs">Mark invested</button></div><div className="mt-4 overflow-auto"><table className="w-full text-xs"><thead className="text-slate-500"><tr><th className="text-left p-2">Date</th><th>Fund</th><th>Units</th><th>Amount</th><th>NAV</th></tr></thead><tbody>{purchases.map((p,i)=>{const f=data.find(x=>x.amfiCode===p.code);return <tr key={i} className="border-t border-white/5"><td className="p-2">{p.date}</td><td>{FUNDS.find(x=>x.amfiCode===p.code)?.shortName}</td><td>{p.units}</td><td>{money(p.amount)}</td><td>{f?f.nav.toFixed(4):"—"}</td></tr>})}</tbody></table></div></div></section>}
